apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq
    newTag: dev-3bb148a69011fd8cd0f6fa26fb42f32d94e89c59

replicas:
  - name: kinetiq
    count: 1