apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq
    newTag: dev-b38f3fb36a632c80ffa48706f4535a6136dc8de6

replicas:
  - name: kinetiq
    count: 1