apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq
    newTag: dev-28195ba1d35dade584b6f7edd81d02c546d5bc3d

replicas:
  - name: kinetiq
    count: 1