apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq-backend
    newTag: dev-latest

replicas:
  - name: kinetiq-backend
    count: 1