apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq-backend
    newTag: dev-c4b3a3ba37f5c32cb53c0488192cb98bf1fd8727

replicas:
  - name: kinetiq-backend
    count: 1