apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq-backend
    newTag: dev-ab0491323a7c9e836c3b853501e464d30e0d8afe

replicas:
  - name: kinetiq-backend
    count: 1