apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kinetiq-backend-prod
  namespace: argocd
spec:
  project: richixs
  source:
    repoURL: git@github.com:Richixs/gitops.git
    targetRevision: main
    path: apps/kinetiq-backend/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: kinetiq-backend-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true