apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kinetiq-backend-develop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Richixs/gitops.git
    targetRevision: main
    path: apps/kinetiq-backend/overlays/develop

  destination:
    server: https://kubernetes.default.svc
    namespace: kinetiq-backend-develop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true