apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-prod-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: portfolio
  source:
    repoURL: git@github.com:Richixs/gitops.git
    targetRevision: main
    path: namespaces/portfolio
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
