apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: portfolio
  namespace: argocd
spec:
  sourceRepos:
    - 'git@github.com:Richixs/gitops.git'
  
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: 'portfolio-*'
  
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: NetworkPolicy
