apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq-backend
    newTag: prod-68c319e5e426008f7ab9b434ace627acf8422a20

replicas:
  - name: kinetiq-backend
    count: 1