apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq-backend
    newTag: prod-7131385973934b90688a7b1f3e7597454825295a

replicas:
  - name: kinetiq-backend
    count: 1