apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq
    newTag: prod-8230232a7852033ecf590b2235780ea7728c06de

replicas:
  - name: kinetiq
    count: 1