apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq
    newTag: prod-f7582935028c4a7788fd854e3f5a48b9d63a618c

replicas:
  - name: kinetiq
    count: 1