apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/richixs/kinetiq
    newTag: prod-aec4c57c6bb62c64e1b58c1f2beceeffd154015f

replicas:
  - name: kinetiq
    count: 1